
/* front.c - a lexical analyster system for ismple arithemtic expressions*/

#include <stdio.h>
#include <ctype.h>

/* Global declarations*/
//Variables:
int charClass;
char lexeme[100];
int line_num;
char nextChar;
char end;
int lexLen;
int token;
int nextToken;
FILE *in_fp, *fopen();
char * x = NULL;

ssize_t holder;
size_t x_len = 0;

//Function Declarations
void addChar();
void getChar();
void getNonBlank();
int lex();

//Character Classes

#define LETTER 0
#define DIGIT 1
#define UNKNOWN 99

//Token codes
#define INT_LIT 10
#define IDENT 11
#define ASSIGN_OP 20
#define ADD_OP 21
#define SUB_OP 22
#define MULT_OP 23
#define DIV_OP 24
#define LEFT_PAREN 25
#define RIGHT_PAREN 26

/*************************************************************************************/
/*main driver*/

int main(int argc, char* argv[])
{
	if(argc != 2) //If the file 
	{
		printf("The file is missing...\n");
		exit(0);
	}
	else if((in_fp = fopen(argv[1], "r")) == NULL)
		printf("ERROR - cannot open front.in");
	/* Open the input data file and process its contents */
	else
	{
		while((holder = getline(&x, &x_len, in_fp)) != EOF)
		{
			lin_num = 0;
			getChar();
			if (x != NULL)
			{
				do{
					lex();
					expr();
				}
				while(nextToken != EOF)
			}
		}
	}

}

/*************************************************************************************/
/* lookup -	a function to lookup operators and parentheses
			and return the token */
int lookup(char ch)
{
	switch (ch){
		case '(':
			addChar();
			nextToken = LEFT_PAREN;
			break;
		case ')':
			addChar();
			nextToken = RIGHT_PAREN;
			break;
		case '+':
			addChar();
			nextToken = ADD_OP ;
		case '-':
			addChar();
			nextToken = SUB_OP;
		case '*':
			addChar();
			nextToken = MULT_OP;
		case '/':
			addChar();
			nextToken = DIV_OP;
		default:
			addChar();
			nextToken = EOF;
			break;
	}
	return nextToken;
}


/*************************************************************************************/
/* addChar -	A function to add nextChar to lexeme. */
void addChar()
{
	if(lexLen < = 98)
	{
		lexeme[lexLen++] = nextChar;
		lexeme[lexLen] = 0;
	}
	else
	{
		printf("ERROR - lexeme is too long\n");
	}
}


/*************************************************************************************/
/* getChar -	a fuction to get the next character of
				input and determine its character class*/

void getChar()
{
	if(x[line_num] != '\n' && x[line_num] != '\0')
	{

		nextChar = x[line_num++];
	
	
		if(isalpha(nextChar))
			charClass = LETTER;
		else if(isdigit(nextChar))
			charClass = DIGIT;
		else if (nextChar == '\n')
			charClass = NEWLINECHAR;
		else
			charClass = UNKNOWN;
	}
	else
		charClass = EOF;
}


/*************************************************************************************/
/* getNonBlank -	a function to call getChar until it
					returns a non-whitespace character */

void getNonBlank()
{
	while(isspace(nextChar))
		getChar();
}


/*************************************************************************************/
/* lex -	a simple lexical analyzer for arithmetic
			expressions. */

int lex()
{

	lexLen = 0;
	getNonBlank();
	end = nextChar;


	switch(charClass){

		/*Parse Identifiers*/
		case LETTER:
			addChar();
			getChar();
			while(charClass == LETTER || charClass == DIGIT)
			{
				addChar();
				getChar();
			}
			nextToken = IDENT;
			break;

		/* Parse integer literals*/
		case DIGIT:
			addChar();
			getChar();
			while(charClass == DIGIT)
			{
				addChar();
				getChar();
			}
			nextToken = INT_LIT;
			break;

		/* Parentheses and operators*/
		case UNKNOWN:
			lookup(nextChar);
			getChar();
			break;

		/*EOF*/
		case EOF:
			nextToken = EOF;
			lexeme[0] = 'E';
			lexeme[1] = 'O';
			lexeme[2] = 'F';
			lexeme[3] = 0;
			break;
		}//end of switch
		
	printf("Next token is: %d, Next Lexeme is: %s\n", nextToken, lexeme);
	return nextToken;
}/* End of function lex*/


/*	expr
	Parses string int he language geenrtaed by the rule:
	<expr> -> <term> {(+|- <term>}
	*/
void expr()
{
	printf("Enter <expr> \n");

	/* Parse the first term*/
	term();

	/* As long as the next token is + or -, get
		the next token and parse the next term*/
	while(nextToken == ADD_OP || nextToken ==SUB_OP)
	{
		lex();
		term();
	}
	printf("Exit <expr>\n");
}// End of functino expr


/*	term 
	Parses strings in the language generated by the rule:
	<term>-> <factor> {(*|/)}
	*/
void term()
{
	printf("Enter <term> \n");

	/* Parse the first factor*/
	factor();

	/* As long as the next token is + or -, get
		the next token and parse the next term*/
	while(nextToken == MULT_OP || nextToken == DIV_OP)
	{
		lex();
		factor();
	}
	printf("Exit <term>\n");
}// End of function term

/*	factor
	Parses strings inthe language generated by the rule:
	<factor> -> id | int_constant | (<expr>)
*/
void factor()
{
	printf("Enter <factor>\n");
	/*Determine which RHS */
	if(nextToken == IDENT || nextToken == INT_LIT)
		//Get the next token
		lex();
	else
	{
		if(nextToken == LEFT_PAREN)
		{
			lex();
			expr();
			if(nextToken == RIGHT_PAREN)
				lex();
			else
				error();
		} // end of if (nextToken == ... ) */
		
		//It was not an id, an integer literal, or a left parenthesis */
		else
			error();
	}// End of else

	printf("Exit <factor>\n");
} // End of function factor



















